### ISSUE TITLE
nginx-devel fails because of 404

### ISSUE THREAD

**Issue by gaborbernat** [dracorp/aur-packages#1]
Hello, 

In the arch repo nginx-devel fails lately because http://web.iti.upv.es/~sto/nginx/ngx_http_auth_pam_module-1.3.tar.gz throws 404. 

Thanks,

**Comment by dracorp** [comment]
I've removed this link but now it's available.

**Comment by gaborbernat** [comment]
Now I get:

==> Verifying source file signatures with gpg...
    nginx-1.7.9.tar.gz ... FAILED (unknown public key 520A9993A1C052F8)

Thanks a lot, 
Bernát

**Comment by dracorp** [comment]
https://wiki.archlinux.org/index.php?&search=makepkg.conf
and
https://wiki.archlinux.org/index.php?&search=gpg

**Comment by gaborbernat** [comment]
And from where can I download the key to import? :) to do the 
gpg --import key.asc

**Comment by dracorp** [comment]
eg. http://pillowfortress.wordpress.com/2012/01/28/public_key_server/
But better will be when I remove this PGP signature.
